[package]
name = "cl-wordle"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Wordle in your terminal"
repository = "https://github.com/conradludgate/wordle"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { version = "0.3", features = ["local-offset", "macros"] }
color-eyre = "0.6"
termion = "1.5"

[[bin]]
name = "wordle"
